### PR TITLE
[9.16.r1] Clang + Stack protector

### PR DESCRIPTION
**Pull request by bartcubbins**
Clang + stack protector fix. Log output fix.

### CODE REVIEW

**Comment by bartcubbins** [comment]
@jerpelea please use this. the one you cherry-picked has a broken commit

**Review by MarijnS95 — APPROVED** [review]
Some long-needed cleanup, thanks!

And let's not forget to port these to 5.10 etc :)

**Comment by MarijnS95** [comment]
Should we trivially port these cleanups to 9.14 too or are all devices EOL on that kernel (i.e. everything is being ported to 9.16)?

**Comment by bartcubbins** [comment]
I sync scripts across all of our kernel versions.
Well, technically I already did that, just need to clean up, commit and push.

**Pull request merged**
